<template>
    <section id="AboutContent">
        <div class="flex-wrap">
            <Logo/>
            <h1>Your available talent</h1>
            <h3>We are starting small and will be expanding the team of experienced minds as the project grows.</h3>
            <ul>
                <li><strong>Rami James</strong> - Product Design and Marketing</li>
                <li><strong>Felipe Faria</strong> - Development and Infrastructure</li>
            </ul>
            <h3>Nodenode.org is run as a decentralized team with all funds generated by the BP services going to the infrastructure and provided services.</h3>
       </div>
    </section>
</template>

<style lang="scss">

#AboutContent {
    ul {
        margin:0;
        padding:20px 0;

        li {
            font-family: 'Poppins';
            font-size:18px;
            list-style:none;
            border-bottom: 2px solid rgba(255,255,255,0.1);
            padding:5px 0;
        }
    }
}

</style>